### ISSUE TITLE
Check-in: Error/Warning

### ISSUE THREAD

**Issue by Mephystus** [LockTar/StyleCop-Check-in-Policy#2]
Hi,
I've installed the latest version, but when I tried to check-in the code, I got the following error:
![image](https://user-images.githubusercontent.com/28352792/29678832-f12af3fe-88f7-11e7-8183-b12f02260a8f.png)

On the check-in panel, I have:
![image](https://user-images.githubusercontent.com/28352792/29678893-2ee23586-88f8-11e7-826d-57b099ba4d98.png)

When I click on the message I got:
![image](https://user-images.githubusercontent.com/28352792/29678933-4501748a-88f8-11e7-872d-56973b0f5800.png)

This was my setup, before installing StyleCop-Check-In-Policy:
- Visual Studio Enterprise 2017 (15.3.2)
- [StyleCop **5.0**.6419.0](https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop)
- ReSharper 2017.1.3, with extension: [StyleCop by JetBrains 2017.1.2-pre001](https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2017.1.2-pre001)

**Comment by LockTar** [comment]
@Mephystus I've tried to reproduce it but without any luck. Do you have a small sample project?

**Comment by Mephystus** [comment]
@LockTar Hi,
This can be closed.

Although it was manifesting in the check-in panel, it's actually a problem with the ReSharper extension: [StyleCop.StyleCop **2017.1.2-pre001**](https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2017.1.2-pre001).

I've uninstalled it and no more issues occurred.
