### ISSUE TITLE
Install on non Community Edition

### ISSUE THREAD

**Issue by wbraun** [LockTar/StyleCop-Check-in-Policy#3]
Should I be able to install this on Visual Studio 2017 Enterprise?

I keep failing at install with  "The extension cannot be installed to this product due to prerequisites that cannot be resolved."  The manifest (shown below) has Community as the Target version and a prerequisite that I might assume is only included in the Community version.  Any ideas?

` <Installation>`
        `<InstallationTarget Version="15.0" Id="Microsoft.VisualStudio.Community" />`
    `</Installation>`
    `<Dependencies>`
        `<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.5,)" />`
    `</Dependencies>`
    `<Assets>`
        `<Asset Type="Microsoft.VisualStudio.VsPackage" d:Source="File" Path="policies.pkgdef" />`
    `</Assets>`
    `<Prerequisites>`
        `<Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0.26606.0,16.0)" DisplayName="Visual Studio core editor" />`
    `</Prerequisites>`

**Comment by LockTar** [comment]
Yes it can be used on every version of VS2017. Please try to install it on a different machine for test. Other people are able to install it on Enterprise (including me).
